version: '3.8'

services:
  time-backend:
    build: ./backend
    container_name: time-backend
    expose:
      - "5000"
    environment:
      - MONGO_URI=mongodb://time-mongo:27017/timetracking
      - NODE_ENV=production
    depends_on:
      - time-mongo
    volumes:
      - ./backend/public/uploads:/app/public/uploads
    networks:
      - farm_network
    restart: unless-stopped

  time-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: time-frontend
    expose:
      - "80"
    depends_on:
      - time-backend
    networks:
      - farm_network
    restart: unless-stopped

  time-mongo:
    image: mongo:6
    container_name: time-mongo
    restart: always
    volumes:
      - time_mongo_data:/data/db
    networks:
      - farm_network

volumes:
  time_mongo_data:

networks:
  farm_network:
    external: true
